# Étape de build
FROM maven:3.9.6-jdk-17 AS build  
WORKDIR /app
COPY springboot-backend/pom.xml .
RUN mvn dependency:go-offline
COPY springboot-backend/src ./src
RUN mvn clean package -DskipTests

# Étape d'exécution
FROM openjdk:17-jdk-slim
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
CMD ["java", "-jar", "app.jar"]